### PR TITLE
[No JIRA] Remove redundant warning

### PR DESCRIPTION
**Pull request by shaundon**
CI covers this and it's visual noise.

### CODE REVIEW

**Comment by k0nserv** [comment]
CI doesn't strictly speaking cover this. This is reminding you that if the component change snapshots should fail. If they don't maybe that's an indication you need to refactor?

**Comment by shaundon** [comment]
Hmm yeah fair point. Maybe we can rephrase the message to make it more relevant.

**Comment by k0nserv** [comment]
Yeah I am not opposed to removing it if the majority are in favour of that, but we should do so for the right reasons

**Comment by shaundon** [comment]
Gonna close for now, it's very minor and we don't have a consensus.

**Pull request closed without merging**
