### PR TITLE
[No JIRA] Update to latest LTS version for node

### PR DESCRIPTION
**Pull request by k0nserv**
This updates the ensure-node-env requirements to

node: ^8.12.0
npm: ^6.4.1

See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.12.0

### CODE REVIEW

**Comment by matthewdavidson** [comment]
There are a whole bunch of package-lock changes in this PR 🤔 is this because of the new version of npm?

**Comment by matthewdavidson** [comment]
You need to update `.nvmrc` too...

**Comment by k0nserv** [comment]
Yes that's my assumption, but I don't really know for sure. Can you try doing the change cleanly from master and see if the same thing happens?

**Comment by matthewdavidson** [comment]
Closing in favour of #1050

**Pull request closed without merging**
