### PR TITLE
Update stylelint to 8.0.0 and stylelint-config-skyscanner to 1.0.0

### PR DESCRIPTION
**Pull request by danrr**

### CODE REVIEW

**Comment by tvooo** [comment]
@k0nserv it seems like the build here did not pick up the new version of stylelint and the config. Can this have something to do with the node_modules cache you mentioned yesterday?

**Comment by danrr** [comment]
No, sorry, forgot to update this. There's a conflict here that caused the npm-shrinkwrap to not be updated.

**Comment by k0nserv** [comment]
The node_modules cache shouldn't have that effect no

**Comment by k0nserv** [comment]
@danrr How did you update `npm-shrinkwrap.json`? It seems like you did `rm npm-shrinkwrap.json && rm -rf node_modules && npm install`?

**Comment by danrr** [comment]
I had to rejigg the version of postcss that gets pulled out as the top module. I didn't delete the shrinkwrap, but I reinstalled a couple things with the same version which caused some interesting side effects, including bumping some minor/patch versions up.

**Comment by k0nserv** [comment]
Hmm it seems like it might have superseded some of the changes @matthewdavidson just merged. Can you rebase please and we should be good to merge

**Comment by danrr** [comment]
Doing that just now

**Comment by danrr** [comment]
Good to go on this.

**Comment by matthewdavidson** [comment]
LGTM 🚢

**Pull request merged**
