### PR TITLE
[BPK-1006] Add Android elevation tokens

### PR DESCRIPTION
**Pull request by matteo-hertel**

### CODE REVIEW

**Comment by matteo-hertel** [comment]
The elevation changed from the hardcoded 3 to elevationSm (4), not a huge difference but still different

**Comment by shaundon** [comment]
@k0nserv I'm pretty sure they are different!

**Comment by matteo-hertel** [comment]
There is a small change that needs to be made so don't merge it

**Comment by matteo-hertel** [comment]
The card elevation has been updated to elevationXs (2 dp)

**Pull request merged**
