### PR TITLE
[KOA-4698] Fix breadcrumb alignment

### PR DESCRIPTION
**Pull request by olliecurtis**
This PR solves the alignment issue of the breadcrumb text to the arrows.

| Before | After |
| -- | -- |
| Screenshot 2021-08-13 at 12 21 35 | Screenshot 2021-08-13 at 12 20 59 |

Remember to include the following changes:

- [x] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack/blob/main/CHANGELOG_FORMAT.md))
- [ ] `README.md`
- [x] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

### CODE REVIEW

**Review by georgegillams — APPROVED** [review]

**Comment by marianeum** [comment]
Is it just me or does it look misaligned now (a bit too high)?

**Comment by olliecurtis** [comment]
> Is it just me or does it look misaligned now (a bit too high)?

So took a look at this during development and it turns out the bottom of the font sits on the same line as the arrow center point

**Comment by marianeum** [comment]
so working as intended?

**Comment by olliecurtis** [comment]
> so working as intended? 

Indeed 🙂 it was the text that had shift vs. the icon, so we need to align the text centrally to its container to sit central

**Review by marianeum — APPROVED** [review]

**Pull request merged**
