### PR TITLE
[BPK-1003] Add flow types to mobile scroll container

### PR DESCRIPTION
**Pull request by matthewdavidson**

### CODE REVIEW

**Comment by matthewdavidson** [comment]
@k0nserv, have a look at the [second commit](https://github.com/Skyscanner/backpack/pull/418/commits/171fcced761080af54e3e4144836af3ee004db5e) - `element.setAttribute` would not work, neither would property setter either (e.g. `element.scollLeft = value;`).

**Comment by k0nserv** [comment]
I see, did the tests fail here?

**Comment by matthewdavidson** [comment]
@k0nserv yes - are you happy with the change?

**Comment by k0nserv** [comment]
Yes :)

**Pull request merged**
