### PR TITLE
[NO-JIRA] Make skip link work without (client-side) JS

### PR DESCRIPTION
**Pull request by georgegillams**
Remember to include the following changes:

- [x] `UNRELEASED.md`
- [x] `README.md`
- [x] Tests
- [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

React 16.4 compatibility:

- [ ] I haven't used Hooks in any code that we ship to consumers.

### CODE REVIEW

**Review by olliecurtis — COMMENTED** [review]
Code looks good will run it locally to try it out! Wish me luck after last time 😆

**Comment by shaundon** [comment]
So essentially you're doing it all with CSS, removing the need for state?

Also I restarted CI so that it'll get deployed to the PRs website

**Comment by shaundon** [comment]
> Also I restarted CI so that it'll get deployed to the PRs website

Actually it needs rebasing before it'll do that, so I just restarted CI for no reason 😓

**Comment by georgegillams** [comment]
> > Also I restarted CI so that it'll get deployed to the PRs website
> 
> Actually it needs rebasing before it'll do that, so I just restarted CI for no reason 😓

I've rebased 👍

**Comment by georgegillams** [comment]
> So essentially you're doing it all with CSS, removing the need for state?
> 
> Also I restarted CI so that it'll get deployed to the PRs website

Exactly - so now it works with JS disabled, and also has less ~bugs~ code for us to maintain

**Review by shaundon — APPROVED** [review]

**Pull request merged**
