### PR TITLE
update preinstall, node

### PR DESCRIPTION
**Pull request by matteo-hertel**
quick change to the `package.json`

you might have to run `nvm use` once this gets merged

the preinstall check has problems with windows npx should help that

### CODE REVIEW

**Comment by k0nserv** [comment]
But now `npx` need to be installed globally? Can't the ensure-node-env check fail because `npx` is missing in the global env you happen to be running?

**Comment by matteo-hertel** [comment]
The latests LTS ships with `npx` installed by default, so if npx failes because is not installed, could be an indicator the node version is not correct, the proof is in the pudding tough, run 
`docker run --rm node:carbon npx -v` should output a version number

**Comment by k0nserv** [comment]
Yeah but the problem is what used to be a nice descriptive error message will now just be `unknown binary npx` on Node < 8 which degrades UX. Further Backpack doesn't strictly speaking support Windows anyway

**Comment by matteo-hertel** [comment]
The correct node version is listed in the getting started guide anyway, if we can remove a brickwall for windows users by having a less user friendly message, I think it's worth it, it also makes the `preinstall` command much neater

**Comment by k0nserv** [comment]
Yeah but in that case can't we use the curl version that works on Windows instead?

**Comment by matteo-hertel** [comment]
I have a version of that curl that works in some windows, beacuse there are tons of different terminal emulators, not all of them implements `curl` the same way, with `npx` will work in a terminal emulator, cmd, power shell etc

**Comment by matteo-hertel** [comment]
Discussed offline, `curl` won over `npx`

**Pull request merged**
