### PR TITLE
[NOJIRA] Lerna ignore bpk-tether

### PR DESCRIPTION
**Pull request by matthewdavidson**
Since [`bpk-tether`](https://github.com/Skyscanner/backpack/tree/master/packages/bpk-tether) isn't used by any other bpk package, we don't need to include it in any lerna operations anymore.
I wanna keep the source in the repo though for any bug fixes that may arise.
```
npm run bootstrap

> backpack@0.0.1 bootstrap /Users/matthewdavidson/projects/backpack
> lerna bootstrap

lerna info version 2.6.0
lerna info versioning independent
lerna info ignore bpk-tether
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "bpk-docs", "react-native-bpk-component-animate-height", "react-native-bpk-component-banner-alert", "react-native-bpk-component-button", "react-native-bpk-component-horizontal-nav", "react-native-bpk-component-spinner", "react-native-bpk-component-switch", "react-native-bpk-theming"
lerna info Bootstrapping 78 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 78 packages


npm run lerna publish

> backpack@0.0.1 lerna /Users/matthewdavidson/projects/backpack
> lerna "publish"

lerna info version 2.6.0
lerna info versioning independent
lerna info ignore bpk-tether
lerna info Checking for updated packages...
lerna info Comparing with bpk-component-image@2.0.11.
lerna info Checking for prereleased packages...
```

### CODE REVIEW

**Comment by k0nserv** [comment]
Should we mark it deprecated? https://docs.npmjs.com/cli/deprecate

**Comment by matthewdavidson** [comment]
> Do we know if it's used by any consumers?

Yes it will be used by all consumers of bpk-component-datepicker<8.0.0, bpk-component-popover<2.0.0 & bpk-component-tooltip<3.0.0.

> If not, do we plan to deprecate it eventually?

Well it pretty much is deprecated - we don't need it anymore.

**Comment by matthewdavidson** [comment]
@matteo-hertel / @shaundon I added another commit https://github.com/Skyscanner/backpack/pull/442/commits/2ba0b2198403917e8a33c7b2e55cdcef12b72a64

**Comment by matthewdavidson** [comment]
> Should we mark it deprecated? https://docs.npmjs.com/cli/deprecate

Yes we should!

**Pull request merged**
