### PR TITLE
[BPK-1286] New home page feature toggle

### PR DESCRIPTION
**Pull request by shaundon**
**To do**
- [x] Add logo to header
- [x] Add last updated (use an env var at build time)
- [x] Needs to look good at all widths
- [x] Test in all browsers
- [x] Align text in hero correctly
- [x] Make footer sticky

**Notes**
- I've named the feature `BPK_NEO` (first thing that popped into my head). To get the new docs site, run `npm run docs:neo` and it'll set an env var.
- Everywhere I've touched that was using `BpkGrid` is now using flexbox.

**Browser tests**

_Windows 10_
- [x] Firefox (latest)
- [x] Edge (latest)
- [x] IE (11)
- [x] Chrome (latest)

_macOS High Sierra_
- [x] Firefox (latest)
- [x] Safari (latest)
- [x] Chrome (latest)

_iOS 11_
- [x] Safari

_Android 8_
- [x] Chrome (Pixel)

### CODE REVIEW

**Comment by georgegillams** [comment]
I've fixed the aspect ratio of the cards at all widths:

**Comment by k0nserv** [comment]
Here's a prebuilt version: 
[dist.zip](https://github.com/Skyscanner/backpack/files/1731854/dist.zip)

# Instructions

1. Unzip
2. cd into the resulting folder
3. `python -m SimpleHTTPServer`
4. Open http://localhost:8000

**Comment by georgegillams** [comment]
And I've made the footer sticky (which was actually an issue with our docs site before!

screen shot 2018-02-16 at 15 30 46
screen shot 2018-02-16 at 15 56 46

**Comment by k0nserv** [comment]
One question here is: Where should we put components related to pages? I notice I've been inconsistent here though

**Comment by shaundon** [comment]
screen shot 2018-02-19 at 13 58 11

Footer is broken on the old/non-neo docs site - have the styles changed for it?

**Comment by k0nserv** [comment]
Yeah they have, but the Footer is a whole new component so I am unsure why that is

**Comment by shaundon** [comment]
> One question here is: Where should we put components related to pages? I notice I've been inconsistent here though

I guess keep them inside `pages/WhateverPage/` until they are used in more than one place, and then refactor them into `components/` - what do you think?

**Comment by shaundon** [comment]
It all looks great to me - I've fixed the merge conflicts and I'll approve once Travis is happy.

**Pull request merged**
