### PR TITLE
[DINGO-1449] Add "sideEffects" hint to all packages

### PR DESCRIPTION
**Pull request by matthewdavidson**
- Based off of previous failed attempt in #1474
- Scoped to `.js` files (or rather blacklist `.css` and `.scss`)

Worth reading the webpack docs for `"sideEffects"` -> https://webpack.js.org/guides/tree-shaking

+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/master/CONTRIBUTING.md)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by matthewdavidson** [comment]
I published some alphas:
```
+ bpk-component-banner-alert@2.0.92-alpha.1
+ bpk-animate-height@1.1.101-alpha.1
+ bpk-component-accordion@1.2.89-alpha.1
+ bpk-component-badge@1.1.79-alpha.1
+ bpk-component-autosuggest@3.0.156-alpha.1
+ bpk-component-barchart@2.3.70-alpha.1
+ bpk-component-breadcrumb@1.0.69-alpha.1
+ bpk-component-breakpoint@1.1.64-alpha.1
+ bpk-component-blockquote@1.1.122-alpha.1
+ bpk-component-button@2.3.6-alpha.1
+ bpk-component-calendar@5.0.9-alpha.1
+ bpk-component-close-button@1.0.131-alpha.1
+ bpk-component-chip@2.0.84-alpha.1
+ bpk-component-checkbox@1.4.96-alpha.1
+ bpk-component-card@1.1.79-alpha.1
+ bpk-component-datatable@0.1.85-alpha.1
+ bpk-component-code@1.1.69-alpha.1
+ bpk-component-content-container@1.3.70-alpha.1
+ bpk-component-description-list@1.0.91-alpha.1
+ bpk-component-datepicker@9.0.10-alpha.1
+ bpk-component-dialog@1.1.58-alpha.1
+ bpk-component-form-validation@2.0.15-alpha.1
+ bpk-component-fieldset@1.1.94-alpha.1
+ bpk-component-drawer@1.2.85-alpha.1
+ bpk-component-grid-toggle@1.1.84-alpha.1
+ bpk-component-heading@2.1.135-alpha.1
+ bpk-component-grid@1.1.135-alpha.1
+ bpk-component-horizontal-nav@2.4.21-alpha.1
+ bpk-component-icon@3.30.1-alpha.1
+ bpk-component-image@2.1.37-alpha.1
+ bpk-component-infinite-scroll@2.2.29-alpha.1
+ bpk-component-input@4.1.13-alpha.1
+ bpk-component-label@3.2.134-alpha.1
+ bpk-component-link@1.2.65-alpha.1
+ bpk-component-list@1.1.105-alpha.1
+ bpk-component-loading-button@2.0.89-alpha.1
+ bpk-component-map@2.5.7-alpha.1
+ bpk-component-modal@1.8.58-alpha.1
+ bpk-component-mobile-scroll-container@1.1.70-alpha.1
+ bpk-component-navigation-bar@1.2.69-alpha.1
+ bpk-component-navigation-stack@1.0.72-alpha.1
+ bpk-component-nudger@1.0.134-alpha.1
+ bpk-component-pagination@1.0.98-alpha.1
+ bpk-component-panel@1.0.128-alpha.1
+ bpk-component-paragraph@1.0.128-alpha.1
+ bpk-component-phone-input@2.0.20-alpha.1
+ bpk-component-popover@2.2.35-alpha.1
+ bpk-component-radio@1.2.94-alpha.1
+ bpk-component-progress@1.0.134-alpha.1
+ bpk-component-router-link@2.0.50-alpha.1
+ bpk-component-rtl-toggle@1.1.84-alpha.1
+ bpk-component-section-list@1.0.68-alpha.1
+ bpk-component-scrollable-calendar@1.0.9-alpha.1
+ bpk-component-slider@1.1.97-alpha.1
+ bpk-component-select@2.2.66-alpha.1
+ bpk-component-spinner@2.2.96-alpha.1
+ bpk-component-star-rating@1.0.130-alpha.1
+ bpk-component-table@1.1.70-alpha.1
+ bpk-component-text@1.0.125-alpha.1
+ bpk-component-textarea@1.1.11-alpha.1
+ bpk-component-ticket@1.2.60-alpha.1
+ bpk-component-tooltip@3.1.80-alpha.1
+ bpk-component-theme-toggle@1.0.104-alpha.1
+ bpk-mixins@17.23.1-alpha.1
+ bpk-react-utils@2.7.9-alpha.11
+ bpk-scrim-utils@3.2.63-alpha.1
+ bpk-stylesheets@3.2.172-alpha.1
+ bpk-svgs@6.7.1-alpha.1
+ bpk-theming@1.2.9-alpha.11
+ bpk-tokens@27.6.3-alpha.11
```

**Comment by matthewdavidson** [comment]
Update: simply scoping the `"sideEffects"` hint to `*.css`/`*.scss` alone is not enough. 

My understanding is that because `"sideEffects"` can impact the JavaScript module graph and therefore the order in which modules are bundled, this in turn affects the order in which and imported css files are bundled.

e.g.

a.js
```
import 'a.css'
```

b.js
```
import a from 'a';
import `b.css`
```

index.js
```
import a from 'a';
import b from 'b';

export default a;

export { b };
```

consumer.js
```
import { b }  from 'index'
```

Without `"sideEffects"` hints, the resulting css would be:
```
<a.css>
...
<b.css>
```

With `"sideEffects"` hints, the resulting css would be:
```
<b.css>
...
<a.css>
```
Whilst `b` imports `a`, in `index.js` a is imported first and without a hint it will be bundled regardless.

**Comment by ajones513** [comment]
I assume that when projects are code split Webpack does not splice the CSS chunks into the DOM in a deliberate (dependency tree-esque?) order, and that it just puts the most recently downloaded chunk at the bottom.

I haven't researched that though, so if anyone knows different or if there's some Webpack config/plugin that means that is a non-issue, please say so!

If my assumption is true, then my thinking is we can't rely on ordering _between files_ anyway.

There is another level to consider too, as I believe that `sideEffects: false` can ruin ordering _within files_ when CSS Modules is used - I believe we've seen a recent example where all parts of the CSS that involved media queries were pushed to the top/bottom of a chunk.

**Comment by matthewdavidson** [comment]
@ajones513, to be clear I am focused on the "within files" issue with my description above (it doesn't take dynamic import chunks into account). However your assumption aligns with my expectations too.

I don't necessarily want to rely on - the whole point of CSS modules is to locally scope style rules so it shouldn't be an issue. But we have experienced this issue with some internal components. I wan't to create a minimal reproducible example - bear with me 😓

**Comment by ojcurtis** [comment]
As per the conversation with Matt we can close this and if required reopen in the future

**Pull request closed without merging**
