### PR TITLE
[NO-JIRA] Make docs footer sticky

### PR DESCRIPTION
**Pull request by georgegillams**
This PR makes the footer stick

Before:
screen shot 2018-02-16 at 17 11 40

After:
screen shot 2018-02-16 at 17 16 55

### CODE REVIEW

**Comment by jamesf3rguson** [comment]
Given we are in the midst of re-building the docs site, I'm not sure how needed this is and if we're better to feed this into the re-design? @k0nserv what do you think?

**Comment by k0nserv** [comment]
I think we should probably do it, but this PR will be have no effect on the new home page. I can incorporate it in the new home page though

**Comment by matthewdavidson** [comment]
Hey @georgegillams! Given that we are on the brink of a redesign and that this is a nice-to-have we are going to close this.

**Comment by georgegillams** [comment]
That's cool. I actully originally implemented this fix on Shaun's new code, and then moved the code accross as I reaslised it was an issue on our existing site too!

**Pull request closed without merging**
