### PR TITLE
[NOJIRA] Generate platform specific extension token files

### PR DESCRIPTION
**Pull request by matthewdavidson**
This PR should allow us to stop doing this:
```
const tokens = Platform.select({
  ios: () => require('bpk-tokens/tokens/ios/base.react.native.common.js'), // eslint-disable-line global-require
  android: () => require('bpk-tokens/tokens/android/base.react.native.common.js'), // eslint-disable-line global-require
})();
```

And start doing this:
```
import { spacingBase } from 'bpk-tokens/tokens/base.react.native';
```

### CODE REVIEW

**Comment by matthewdavidson** [comment]
Yeah that was intentional and no it's not part of the public interface.

**Comment by matteo-hertel** [comment]
Will this cause problems during testing? e.g. Jest not loading the correct tokens and loading always iOS

**Comment by matthewdavidson** [comment]
@matteo-hertel yes ... yes it will 😂

**Comment by matteo-hertel** [comment]
raining_david_tennant

**Pull request merged**
