### PR TITLE
[BPK-3340] Changed textEmphasizedFontWeight to 700

### PR DESCRIPTION
**Pull request by shaundon**

### CODE REVIEW

**Comment by tiagoengel** [comment]
Does it make RN use the correct font variation?

**Comment by shaundon** [comment]
@tiagoengel I think so - RN reads this token so this should filter down

**Comment by tiagoengel** [comment]
> @tiagoengel I think so - RN reads this token so this should filter down

What I meant is, will setting the font weight to 700 result in using `relative-bold`?

**Comment by shaundon** [comment]
Ah sorry. I manually changed the font weight to 700 in the app and it did make it look fine. I'll DM you a link

**Pull request merged**
