### PR TITLE
Native picker component contribution

### PR DESCRIPTION
**Pull request by MichaelTkachuk**

### CODE REVIEW

**Comment by matthewdavidson** [comment]
Hey @MichaelTkachuk! Thanks for the PR! I pushed a commit to surface the picker story in the storybook.

Few things (screenshots below):
- there are some prop type warnings in the storybook
- the android picker menu looks broken
- I reckon we'll want to use the [new button link](https://backpack.github.io/components/native/button-link/) in the picker menu (this will be released soon)

screenshot_1519904712
screenshot_1519905700
simulator screen shot - iphone 8 - 2018-03-01 at 12 01 49

**Comment by MichaelTkachuk** [comment]
Nice one @matthewdavidson I just copied some code across, probably missed out on some of the styling. Will fix those small issues.

**Comment by MichaelTkachuk** [comment]
@matthewdavidson @shaundon I've fixed the issues on screenshots, looks like I've accidentally imported BPK tokens from wrong location. Also I've added readme.md there with some explanation on how to use the picker.

Hope it'll work this time!

**Comment by shaundon** [comment]
Closing in favour of https://github.com/Skyscanner/backpack/pull/599, which includes these changes plus more.

**Pull request closed without merging**
