### PR TITLE
NO-JIRA: Accessibility improvements for BpkHorizontalNav

### PR DESCRIPTION
**Pull request by andresmoritan**
# Context
After implementing the latest version of `BpkHorizontalNav` on the `VerticalTabs` component of the new travel homepage and running some manual tests on accessibility, we found some issues that prevent the component to be fully functional by a traveller using a screen reader to navigate.
This PR introduces the necessary changes to address those issues and offer a completely accessible experience for the `BpkHorizontalNav` component.

## Current state
**[Accessibility recording](https://skyscanner.slack.com/files/UNFFYS0T0/F015WTBADV4/bpkhorizontalnav-a11y-current.mov)**
- ⚠️ It's not possible to focus on the selected tab, preventing the user to know which tab is selected and what's the title of that tab.
- ⚠️ It's not possible to select a tab following the screen reader instructions (⌃ ⌥ Space), preventing the user to navigate properly across the different tabs.

## Upgraded state
**[Accessibility recording](https://skyscanner.slack.com/files/UNFFYS0T0/F0163KVV5FU/bpkhorizontalnav-a11y-fixed.mov)**
- ✅ It's possible to focus on the selected tab, telling the user on the beginning of the navigation which tab is selected and what's the title of that tab.
- ✅ It's possible to select a tab following the screen reader instructions (⌃ ⌥ Space), enabling the user to navigate properly across the different tabs.

# Changes
- Switch the ARIA attributes to the clickable element instead of containers.
- Avoid disabling the clickable elements when the tab is selected.
- Replace unnecessary list containers (`<ul>` and `<li>`) with non-semantic ones.

Supporting documentation for this changes can be found on [this document](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role).

Remember to include the following changes:
+ [x] `UNRELEASED.yaml`
+ [x] `README.md`
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

### CODE REVIEW

**Comment by shaundon** [comment]
Hey 👋 This looks fantastic, I love the super-detailed PR description and attached videos!

It's just me working today on the web side of things — I'll try and review it today but it might end up being Monday.

**Comment by andresmoritan** [comment]
> Hey 👋 This looks fantastic, I love the super-detailed PR description and attached videos!
> 
> It's just me working today on the web side of things — I'll try and review it today but it might end up being Monday.

Great @shaundon, thanks! Glad you like it (it's my first one to Backpack).
Next week is perfect, there is no hurry on our side because we are using it in a place that's not being released yet.

**Comment by shaundon** [comment]
I'm so sorry, this massively slipped through the cracks! I'm reviewing it now.

**Review by shaundon — APPROVED** [review]
Ran locally and looks good to me! Again, so sorry for letting this slip through the cracks 🤦

**Pull request merged**
