### PR TITLE
[BPK-693] Add gulp step to set correct SVG permission

### PR DESCRIPTION
**Pull request by georgegillams**

### CODE REVIEW

**Comment by k0nserv** [comment]
Shouldn't this also include a bunch of changes to the svgs?

**Comment by k0nserv** [comment]
I ran this locally and it didn't produce a change which brings the question why is this needed? cc @matthewdavidson

**Comment by georgegillams** [comment]
The icon svgs all have the correct permissions, so this should not change them. If you 'chmod +x *' in one of the directories and then rebuild you should find the output ones lose executableness

**Comment by tvooo** [comment]
To clarify: as this is async, on some runs the output will have bad permissions, and sometimes it won't, which then ends as a change in git even though nothing changed in the source.

**Comment by k0nserv** [comment]
Right that makes sense then, LGTM 👍

**Pull request merged**
