### PR TITLE
[no jira] Rename left/right in native badge to start/end

### PR DESCRIPTION
**Pull request by shaundon**
* Also made the readme example code use the `BADGE_TYPES` and `BADGE_DOCKED_TYPES` enums.
* Redid screenshots so that web and native look much closer (see below).

**Web**
web

**Native**
native

### CODE REVIEW

**Comment by k0nserv** [comment]
Does this actually work in RTL? I'm thinking specifically about the left/right borders not being correct in RTL

**Comment by shaundon** [comment]
Forgot to check that, one moment and I'll confirm.

**Comment by shaundon** [comment]
RTL is all good!

**Comment by k0nserv** [comment]
It is? I would think that the outline version when docked would do the wrong thing when removing the borders for example

**Comment by shaundon** [comment]
Android screenshots with RTL enabled:

screenshot_1520328895
screenshot_1520328900

**Comment by k0nserv** [comment]
Intersting, so that means that the left/right wording in the border properties also correct for RTL then

**Comment by shaundon** [comment]
Yeah, RN just intelligently inverts it all - Matteo was extolling its virtues last week 😆

**Pull request merged**
