### PR TITLE
Revert "Use BpkInfiniteScroll instead of react-virtualized"

### PR DESCRIPTION
**Pull request by MoOmEeN**
what: revert scrollable calendar back to using react-virtualized,
why: new implementation has a bug of not automatically scrolling to the selected day. also the experience is not good

we are working on improving the component here: 
https://gojira.skyscanner.net/browse/TSS-4044
https://gojira.skyscanner.net/browse/BPK-2083

### CODE REVIEW

**Comment by matthewdavidson** [comment]
Hey - thanks for this. If we refer back to the original PR to introduce `bpk-component-infinite-scroll` (https://github.com/Skyscanner/backpack/pull/1141/files), there is a change that moves the following prop assignment from `DateComponent` to `DateContainer`:
```
isEmptyCell={!isSameMonth(date, month) && ignoreOutsideDate}
```

(See https://github.com/Skyscanner/backpack/pull/1141/files#diff-b09d1b032e5b98fd4593b1ffd3b0ff36R148)

I'm not close to this work so I've not looked into the details ... any idea why this wasn't also reverted? oversight perhaps?

**Comment by matthewdavidson** [comment]
On closer inspection, `isEmptyCell` is defined on `DateContainer` so this must have just been fixed in the original PR.

**Comment by matthewdavidson** [comment]
I rebased it for you :)

**Comment by MoOmEeN** [comment]
thanks @matthewdavidson, yep, I left this as this property is required on `DateContainer`, not `BpkCalendarDate`

**Pull request merged**
